### ISSUE TITLE
Change "disapprove" to "reject" everywhere

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/milestonetracker#1]
:-) Sounds better

**Comment by GriffGreen** [comment]
Also for clarity, it would be nice to explicitly call out the arbitration functions:

forceApproveMilestone(uint _idMilestone) => arbitrateApproveMilestone(uint _idMilestone) 

cancelCampaign() => arbitrateCancelCampaign()

**Comment by jbaylina** [comment]
Done!
