### ISSUE TITLE
Name changes and thoughts on Milestone Tracker

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/milestonetracker#2]
Remember to ctrl-f and replace within the javascript helperfile and any other documents you think might have these terms in them! :-)

Cancelled = Canceled (American preference) this is in a lot of random places :-)

payDestination = paymentSource

approveMilestone() = approveCompletedMilstone()

collectMilestone() = collectMilestonePayment()

CampaignCalncelled = CampaignCanceled

milestone enums:
0= notdone = Accepted&InProgress   
1=done = completed

**Comment by jbaylina** [comment]
Completed!! :)
